services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      # so code changes reflect immediately in dev
      - ./api:/app/api
    environment:
      - FLASK_ENV=development

  web:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./app:/app
      - /app/node_modules
    command: |
      sh -c "pnpm install && pnpm run dev"
    ports:
      - "3000:3000"
    depends_on:
      - api
