# nixpacks.toml

# 1) Override providers to only run Python
providers = ['python']

# 2) (Optional) add any extra Nix packages you need,
#    e.g. git, curl, or system libraries
[phases.setup]
nixPkgs = ['python311', 'git']        # python311 is default anyway

# 3) Install your Python deps
[phases.install]
cmds = ['pip install -r requirements.txt']

# 4) (You can leave build empty if you don't need a build step)
[phases.build]
cmds = []

# 5) How to start your Flask app
[start]
cmd = 'gunicorn api.app:app --bind 0.0.0.0:8080'
